### ISSUE TITLE
When in nuget dependency will be shown as unsupported

### ISSUE THREAD

**Issue by xplatsolutions** [DaveSenn/Extend#6]
When referencing to a .NET Standard 2.0 project and deployed as nuget dependency for my nuget, it will not installed and shown as unsupported!

**Comment by DaveSenn** [comment]
You have a NET Standard 2.0 project which references Extend.
When adding your project (using NuGet) to another project, Extend will not be installed correctly?
Do I understand this correctly?

I’ve some (private) projects referencing Extend, which are also deployed as NuGet package… and I don’t have any issues with these packages.

Can you please add your NuGet package to the issue?

**Comment by xplatsolutions** [comment]
Yes this is the issue.
Let me try with latest version and get back to you.

**Comment by xplatsolutions** [comment]
Here is the nuget package, `devops are using pack -c Release /p:PackageVersion=${bamboo.CPVersion_PersonalLinesInsights_Autoupdate}.${bamboo.buildNumber}${bamboo.Nuget.package.suffix}` to build the package.

https://file.io/4GkxN5

I'm trying to create one solution with different flavors, let me know if you see anything strange. I can see now that the dependency is pulled but Visual Studio shows the below.

![image](https://user-images.githubusercontent.com/10971321/40802735-841af8a8-64e4-11e8-95ba-7cfd69a0530c.png)

**Comment by DaveSenn** [comment]
Thanks for your reply. 
I tried to download your package but the URL ends in a 404.

I then tried to reproduce your problem:

1.	I’ve created a .NET Standard 2.0 Library which references the Extend NuGet package
2.	Enabled package “Generate NuGet package on build” for that project
3.	Build the .NET Standard 2.0 project
4.	Published the generated NuGet package on a NuGet feed
5.	Created a .NET 4.6.1 (minimum requirement for .NET Standard 2.0) project and referenced my new NuGet package

I could build my .NET 4.6.1 project and everything worked.

![issue6_edit](https://user-images.githubusercontent.com/7510324/40827527-2022978a-657e-11e8-9b84-51c5ff3fbd2c.png)


I noticed a **strange difference**.
For my package VS did list .NETStandard v2.0 as dependency (which I guess is correct).
On your screenshot this dependency is missing… maybe that is the problem?

In the nuspec file generated for the new NuGet package extend is listed as a dependency:

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>MyNetStandard20Lib</id>
    <version>1.0.0</version>
    <authors>MyNetStandard20Lib</authors>
    <owners>MyNetStandard20Lib</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <dependencies>
      <group targetFramework=".NETStandard2.0">
        <dependency id="extend" version="1.2.1" exclude="Build,Analyzers" />
      </group>
    </dependencies>
  </metadata>
</package>
```

As far as I can tell everything looks ok.

Can check if my new NuGet package [MyNetStandard20Lib.1.0.0.nupkg.zip](https://github.com/DaveSenn/Extend/files/2061549/MyNetStandard20Lib.1.0.0.nupkg.zip) works with your project (maybe we have a NuGet version issue? Btw. I’m using NuGet 4.4.1 / VS 15.7.3)
_Please note: I had to add the extension .zip to be able to attach the package to the issue_

If you can’t or don’t want to host the package for testing… I’ve another NuGet package which references Extend: [Stomp.Net](https://www.nuget.org/packages/Stomp.Net/) (It’s a .NET Standard 1.3 library)

Maybe you could check if this package installs correctly in your project.

**Comment by xplatsolutions** [comment]
Hey Dave, having some blockers by our devops to move forward with this :-/

**Comment by DaveSenn** [comment]
@xplatsolutions Have you tested with the other package. Does it work?

**Comment by DaveSenn** [comment]
Closed as inactive.
